### ISSUE TITLE
embeddable?

### ISSUE THREAD

**Issue by alanpaulkwan** [IMSMWU/RClickhouse#59]
Crazy idea. With the advent of clickhouse-client, I'm wondering if it's plausible to embed Clickhouse like SQLite. Parquet backend?

**Comment by inkrement** [comment]
Hi, I like the Idea and also thought about a similar feature some months back. However, there are some remarks from my side: First, this package is build on the c++-client and not the cli-client. Therefore, this would require to build a completely new package. Due to all requirements, this will likely to end in a quite "fat" package. Secondly, there exists already similar packages/solutions for R (e.g., [duckdb](http://www.duckdb.org)). And they are already tuned for such use cases. Finally, ClickHouse is build for massive datasets with vertical and horizontal scalability in mind. Therefore, a embeddable version may not satisfy the target group and may limit it in may ways. 

I'll close this issue for now, but feel free to reopen it anytime.
